version: '3'

services:
  prioq-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/prioq-cpython:0.1.1
    volumes:
      - ./prioq/:/opt/prioq/prioq/
      - ./tests/:/opt/prioq/tests/
      - ./README.md:/opt/prioq/README.md
      - ./requirements.txt:/opt/prioq/requirements.txt
      - ./requirements-tests.txt:/opt/prioq/requirements-tests.txt
      - ./setup.py:/opt/prioq/setup.py
      - ./pytest.ini:/opt/prioq/pytest.ini
    entrypoint: pytest
