version: '3'

services:
  prioq-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/prioq-pypy:0.5.0-alpha
    volumes:
      - ./prioq:/opt/prioq/prioq
      - ./pytest.ini:/opt/prioq/pytest.ini
      - ./README.md:/opt/prioq/README.md
      - ./requirements-tests.txt:/opt/prioq/requirements-tests.txt
      - ./requirements.txt:/opt/prioq/requirements.txt
      - ./setup.py:/opt/prioq/setup.py
      - ./tests:/opt/prioq/tests
    entrypoint: pytest
