version: '3'

services:
  prioq-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/prioq-cpython:0.4.0
    volumes:
      - ./prioq:/opt/prioq/prioq
      - ./pytest.ini:/opt/prioq/pytest.ini
      - ./README.md:/opt/prioq/README.md
      - ./requirements-tests.txt:/opt/prioq/requirements-tests.txt
      - ./requirements.txt:/opt/prioq/requirements.txt
      - ./setup.py:/opt/prioq/setup.py
      - ./tests:/opt/prioq/tests
    entrypoint: pytest
