version: '3'

services:
  prioq-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/prioq-pypy:0.6.0-alpha
    volumes:
      - ./prioq:/opt/prioq/prioq
      - ./pyproject.toml:/opt/prioq/pyproject.toml
      - ./README.md:/opt/prioq/README.md
      - ./setup.py:/opt/prioq/setup.py
      - ./tests:/opt/prioq/tests
    entrypoint: pytest
