version: '3'

services:
  prioq-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/prioq-cpython:0.6.0
    volumes:
      - ./prioq:/opt/prioq/prioq
      - ./pyproject.toml:/opt/prioq/pyproject.toml
      - ./README.md:/opt/prioq/README.md
      - ./setup.py:/opt/prioq/setup.py
      - ./tests:/opt/prioq/tests
    entrypoint: pytest
